CMD={MOVE=10,FIGHT=16,STOP=0,INSERT=1,REMOVE=2,REPAIR=40,RECLAIM=90,OPT_ALT=128,OPT_CTRL=64,OPT_META=4,OPT_SHIFT=32,OPT_RIGHT=16}
Game={mapSizeX=8000,mapSizeZ=8000}
WG={}; widgetHandler={CommandNotify=function()return false end,UnitCommandNotify=function()return false end}
clock=10; calls={}; units={}; queues={}
UnitDefs={[1]={name='test',humanName='Test Raider',iconType='kbotraider',speed=90,xsize=2,zsize=2,metalCost=65,maxWeaponRange=180}}
for id=1,12 do units[id]={x=1000+id*64,z=1000,def=1,team=0} end
Spring={Utilities={CMD={RAW_MOVE=31109}},GetGameSeconds=function()return clock end,GetGameFrame=function()return clock*30 end,GetSpectatingState=function()return false end,IsReplay=function()return false end,GetMyTeamID=function()return 0 end,GetMyAllyTeamID=function()return 0 end,ValidUnitID=function(id)return units[id]~=nil end,GetUnitIsDead=function()return false end,GetUnitTeam=function(id)return units[id] and units[id].team end,GetUnitDefID=function(id)return units[id] and units[id].def end,GetUnitPosition=function(id)local u=units[id];if u then return u.x,0,u.z end end,GetGroundHeight=function()return 0 end,GetSelectedUnits=function()return {1,2,3,4} end,GetCommandQueue=function(id)return queues[id] or {} end,GiveOrderToUnit=function(id,cmd,p,o) calls[#calls+1]={id=id,cmd=cmd,p=p,o=o}; if cmd~=CMD.INSERT then queues[id]={{id=cmd,params=p,tag=#calls,options={}}} end; return true end,Echo=function()end,GetUnitRulesParam=function()return nil end,GetUnitTransporter=function()return nil end,GetUnitHealth=function()return 100,100,0,0,1 end,GetUnitLosState=function()return {los=true} end,GetPositionLosState=function()return true end,GetTeamUnits=function()return {1,2,3,4} end,GetAllUnits=function()return {1,2,3,4} end,GetTeamResources=function()return 1000,2000,5,10,5 end,GetTeamRulesParam=function()return nil end}
function loadModule(n)return dofile(ROOT..'/LuaUI/Widgets/Include/CommandLayer/'..n..'.lua') end
C={U=loadModule('Util')}; C.settings=loadModule('Settings')(C.U); C.settings.formation='LINE'; C.debug=loadModule('Debug')(C.U)
for _,pair in ipairs({{'classify','UnitClassification'},{'registry','ForceRegistry'},{'formations','Formations'},{'orders','Orders'},{'officer','Officer'},{'retreatPriority','RetreatPriority'},{'routing','Routing'},{'mapControl','MapControl'}}) do C[pair[1]]=loadModule(pair[2])(C) end
